// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagement.Infrastructure.Data;

#nullable disable

namespace VisitorManagement.Infrastructure.Migrations
{
    [DbContext(typeof(VisitorManagementApplicationContext))]
    partial class VisitorManagementApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VisitorManagement.Domain.Common.AdminApprovalStatus", b =>
                {
                    b.Property<int>("HostVisitorRequestId")
                        .HasColumnType("int");

                    b.Property<string>("AdminFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("HostVisitorRequestId");

                    b.ToTable("AdminApprovalStatuses");
                });

            modelBuilder.Entity("VisitorManagement.Domain.Common.HostVisitorRequest", b =>
                {
                    b.Property<int>("HostVisitorRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostVisitorRequestId"), 1L, 1);

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("VisitDuration")
                        .HasColumnType("time");

                    b.Property<DateTime>("VisitorArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitorCheckOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorVisitPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HostVisitorRequestId");

                    b.ToTable("HostVisitorRequests");
                });

            modelBuilder.Entity("VisitorManagement.Domain.Common.VisitorEntity", b =>
                {
                    b.Property<string>("VisitorName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<string>("VisitorContactNumber")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(3);

                    b.Property<int>("VisitorEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitorEntityId"), 1L, 1);

                    b.Property<string>("VisitorPersonalIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisitorPersonalIdType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorName", "VisitorContactNumber");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("VisitorManagement.Domain.Common.AdminApprovalStatus", b =>
                {
                    b.HasOne("VisitorManagement.Domain.Common.HostVisitorRequest", "HostVisitorRequest")
                        .WithMany("AdminApprovalStatuses")
                        .HasForeignKey("HostVisitorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostVisitorRequest");
                });

            modelBuilder.Entity("VisitorManagement.Domain.Common.HostVisitorRequest", b =>
                {
                    b.Navigation("AdminApprovalStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
